# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac07f07d51ae1c1098d14bf3e624716f58005d159928ec473a33deb6edb06e1edf582ad20d7d3d1f2e5795e174e20b2e782c273c7bd739896a3775c5f3cc6cab

test:
  secret_key_base: 0326816b89db5485166f63413e07c74630c0557fccaca01e0c36babbfc4acb5b956aee4f4e058fd83d14007ea4210e3fcc2fae380c7fed110c32150d0b49500f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
